name: myfirst job
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: installing node modules
        run: npm ci
      - name: build next.js application
        run: npm run build
            # Add this step directly underneath your build execution command
      - name: Upload production build files
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build-artifact   # The download package name
          path: |
            .next
            public
            package.json
  deploy:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      # Retrieve the verified build bundle from Job 1
      - name: Download compiled bundle
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build-bundle

      - name: Execute cloud deployment
        run: |
          echo "Connecting to production servers..."