name: myfirst job
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: action/checkout@v3
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: installing node modules
        run: npm install
      - name: build next.js application
        run: npm run build
